//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Agent
    {
        PopryzhenokDBEntities context = new PopryzhenokDBEntities();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.SalePoint = new HashSet<SalePoint>();
        }
    
        public int AgentId { get; set; }
        public int AgentTypeID { get; set; }
        public string YridAddres { get; set; }
        public string INN { get; set; }
        public string CPP { get; set; }
        public string DirectorFIO { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public string Priority { get; set; }
        public Nullable<int> RealizationHistoryID { get; set; }
        public string AgentName { get; set; }

        public string LogoDisplay 
        { 
            get
            {
                return "../Resources/" + this.Logo;
        
            }   
        }

        public string Prodaji
        {
            get
            {
                var a = context.ProductSale.Where(x => x.AgentId ==  this.AgentId).FirstOrDefault().CountProduction;
                return "Продажи за год " + a.ToString();

            }
        }

        public virtual AgentsType AgentsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalePoint> SalePoint { get; set; }
    }
}
