//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Supplier = new HashSet<Supplier>();
        }
    
        public int MaterialID { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
        public int CountInPocket { get; set; }
        public int UnitTypeID { get; set; }
        public Nullable<int> CountInSrorage { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> Cost { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual UnitType UnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Supplier { get; set; }
    }
}
