//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Article { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> PocketSizeID { get; set; }
        public Nullable<int> WeightWihtoutPocket { get; set; }
        public Nullable<int> WeifhtWithPocket { get; set; }
        public byte[] Sertificate { get; set; }
        public Nullable<int> StandartNumberID { get; set; }
        public string CountPeopleForProizv { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumberOfShop { get; set; }
        public Nullable<int> MinCostForAgent { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual Standart Standart { get; set; }
    }
}
