//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int ProductSaleID { get; set; }
        public int ProductId { get; set; }
        public int AgentId { get; set; }
        public Nullable<System.DateTime> RealizationDate { get; set; }
        public Nullable<int> CountProduction { get; set; }
    }
}
