//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePoint
    {
        public int SalePointID { get; set; }
        public string Name { get; set; }
        public Nullable<int> AgentID { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
