//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popryzhenok
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int SupplierID { get; set; }
        public string Name { get; set; }
        public string INN { get; set; }
        public Nullable<int> SupplierTypeID { get; set; }
        public Nullable<int> MaterialID { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual SupplierType SupplierType { get; set; }
    }
}
